extends Node

const _defaults: Dictionary[String, Variant] = {
	"PLAYER_MVMT_SPEED": 70,
	"PLAYER_CRIT_CHANCE": 0,
	"PLAYER_IS_IMMUNE": false,

	"ENEMY_MVMT_SPEED": 20,
	"ENEMY_IS_IMMUNE": false,

	"PLAYER_PROJECTILE_SPEED": 40,
	"PLAYER_PROJECTILE_PIERCE": 0,
	"PLAYER_PROJECTILE_BOUNCE": 0,
	"PLAYER_PROJECTILE_HOMING": false,

	"ENEMY_PROJECTILE_SPEED": 40,
	"ENEMY_PROJECTILE_PIERCE": false,
	"ENEMY_PROJECTILE_BOUNCE": 0,
	"ENEMY_PROJECTILE_HOMING": false,

	"PLAYER_TARGETS_PROJECTILES": false,
	"ENEMY_TARGETS_PROJECTILES": false,
	"ENEMY_TARGETS_ENEMY": false,
}

var PLAYER_MVMT_SPEED: float = _defaults["PLAYER_MVMT_SPEED"]
var PLAYER_IS_IMMUNE: bool = _defaults["PLAYER_IS_IMMUNE"]
var PLAYER_CRIT_CHANCE: float = _defaults["PLAYER_CRIT_CHANCE"]

var ENEMY_MVMT_SPEED: float = _defaults["ENEMY_MVMT_SPEED"]
var ENEMY_IS_IMMUNE: bool = _defaults["ENEMY_IS_IMMUNE"]

var PLAYER_PROJECTILE_SPEED: float = _defaults["PLAYER_PROJECTILE_SPEED"]
var PLAYER_PROJECTILE_PIERCE: int = _defaults["PLAYER_PROJECTILE_PIERCE"]
var PLAYER_PROJECTILE_BOUNCE: int = _defaults["PLAYER_PROJECTILE_BOUNCE"]
var PLAYER_PROJECTILE_HOMING: bool = _defaults["PLAYER_PROJECTILE_HOMING"]

var ENEMY_PROJECTILE_SPEED: float = _defaults["ENEMY_PROJECTILE_SPEED"]
var ENEMY_PROJECTILE_PIERCE: bool = _defaults["ENEMY_PROJECTILE_PIERCE"]
var ENEMY_PROJECTILE_BOUNCE: int = _defaults["ENEMY_PROJECTILE_BOUNCE"]
var ENEMY_PROJECTILE_HOMING: bool = _defaults["ENEMY_PROJECTILE_HOMING"]

var PLAYER_TARGETS_PROJECTILES: bool = _defaults["PLAYER_TARGETS_PROJECTILES"]
var ENEMY_TARGETS_PROJECTILES: bool = _defaults["ENEMY_TARGETS_PROJECTILES"]
var ENEMY_TARGETS_ENEMY: bool = _defaults["ENEMY_TARGETS_ENEMY"]

var num_instances_active: Dictionary[Card.ID, int] = {
	# Player-affecting
	Card.ID.PLAYER_SPEED_10: 0,
	Card.ID.PLAYER_SPEED_10_NEGATIVE: 0,
	Card.ID.PLAYER_SPEED_20: 0,
	Card.ID.PLAYER_SPEED_20_NEGATIVE: 0,
	Card.ID.PLAYER_SPEED_30: 0,
	Card.ID.PLAYER_SPEED_30_NEGATIVE: 0,
	Card.ID.PLAYER_DAMAGE_IMMUNE: 0,
	Card.ID.PLAYER_CRIT_CHANCE_10: 0,
	Card.ID.PLAYER_CRIT_CHANCE_20: 0,
	Card.ID.PLAYER_CRIT_CHANCE_30: 0,


	# Enemy-affecting
	Card.ID.ENEMY_SPEED_10: 0,
	Card.ID.ENEMY_SPEED_10_NEGATIVE: 0,
	Card.ID.ENEMY_SPEED_20: 0,
	Card.ID.ENEMY_SPEED_20_NEGATIVE: 0,
	Card.ID.ENEMY_SPEED_30: 0,
	Card.ID.ENEMY_SPEED_30_NEGATIVE: 0,
	Card.ID.ENEMY_DAMAGE_IMMUNE: 0,


	# Projectiles
	Card.ID.PLAYER_PROJECTILE_SPEED_10: 0,
	Card.ID.PLAYER_PROJECTILE_SPEED_10_NEGATIVE: 0,
	Card.ID.PLAYER_PROJECTILE_PIERCE_1: 0,
	Card.ID.PLAYER_PROJECTILE_PIERCE_2: 0,
	Card.ID.PLAYER_PROJECTILE_PIERCE_3: 0,
	Card.ID.PLAYER_PROJECTILE_BOUNCE_1: 0,
	Card.ID.PLAYER_PROJECTILE_HOMING: 0,

	Card.ID.ENEMY_PROJECTILE_SPEED_10: 0,
	Card.ID.ENEMY_PROJECTILE_SPEED_10_NEGATIVE: 0,
	Card.ID.ENEMY_PROJECTILE_PIERCE_BUT_FF: 0,
	Card.ID.ENEMY_PROJECTILE_BOUNCE_1: 0,
	Card.ID.ENEMY_PROJECTILE_HOMING: 0,


	# Targeting
	Card.ID.PLAYER_TARGETS_PROJECTILES: 0,
	Card.ID.ENEMY_TARGETS_PROJECTILES: 0,
	Card.ID.ENEMY_TARGETS_ENEMY: 0,
}
